#!/usr/bin/env bash
# Rotate the certificate authority this box uses to intercept your own traffic.
#
#   ./rotate-ca.sh            rotate (asks first, backs the old one up)
#   ./rotate-ca.sh --check    show the current certificate and what would happen
#
# WHY: the CA is valid for ~10 years. If anyone ever quietly copied the SD card, they'd
# hold a working key for a decade. Theft you'd notice; a quiet copy you would not.
# Rotating yearly means an old copy stops being useful.
#
# COST: every routed device must install the new certificate. Until it does, browsing on
# that device fails with certificate warnings. Do this when you have ten minutes.
set -euo pipefail

CONF="${COOLDOWN_CONFDIR:-/var/lib/cooldown/mitmproxy}"
BACKUPS="${COOLDOWN_BACKUP_DIR:-/var/backups/cooldown}"
PROXY_USER="${COOLDOWN_PROXY_USER:-cooldownproxy}"
SERVICE="${COOLDOWN_PROXY_SERVICE:-cooldown-proxy}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -t 1 ]; then B=$'\e[1m'; DIM=$'\e[2m'; G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; C=$'\e[36m'; N=$'\e[0m'
else B=""; DIM=""; G=""; Y=""; R=""; C=""; N=""; fi
say()  { printf "  %s\n" "$*"; }
ok()   { printf "  ${G}✓${N} %s\n" "$*"; }
die()  { printf "\n${R}✗ %s${N}\n" "$*" >&2; exit 1; }

fingerprint() { sudo openssl x509 -in "$1" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2; }

[ "$(id -u)" -eq 0 ] && die "Run as your normal user, not root — it will use sudo when needed."
sudo test -f "$CONF/mitmproxy-ca.pem" || die "No certificate found at $CONF — is this the right box?"

printf "\n${B}Current certificate${N}\n"
say "location:    $CONF"
say "fingerprint: $(fingerprint "$CONF/mitmproxy-ca-cert.pem")"
sudo openssl x509 -in "$CONF/mitmproxy-ca-cert.pem" -noout -dates | sed 's/^/  /'
# A CA generated before name constraints existed can vouch for any host on the internet.
# Say so plainly: it is the difference between a stolen key costing you Reddit and a
# stolen key costing you everything.
NCOUNT="$(sudo openssl x509 -in "$CONF/mitmproxy-ca-cert.pem" -noout -text \
          | sed -n '/Name Constraints/,/Excluded/p' | grep -c 'DNS:' || true)"
if [ "${NCOUNT:-0}" -gt 0 ]; then
  say "scope:       constrained to $NCOUNT gated domains"
else
  printf "  ${Y}scope:       UNCONSTRAINED — can vouch for any host on the internet${N}\n"
  say "             rotating now replaces it with a constrained one"
fi

if [ "${1:-}" = "--check" ]; then
  printf "\n${DIM}--check only. Re-run without it to rotate.${N}\n"; exit 0
fi

cat <<EOF

${Y}${B}This replaces the certificate your devices trust.${N}
  · Every routed device (phone, laptop) must install the NEW one afterwards.
  · Until it does, ${B}HTTPS on that device will fail${N} with warnings.
  · The old key is backed up, so this is reversible if something goes wrong.
EOF
read -r -p "  ${B}Type 'rotate' to continue:${N} " ans </dev/tty || true
[ "$ans" = rotate ] || die "Cancelled — nothing changed."

STAMP="$(date +%Y-%m-%d-%H%M%S)"
OLD="$BACKUPS/ca-$STAMP"
printf "\n${B}Rotating${N}\n"
sudo mkdir -p "$BACKUPS"
sudo cp -a "$CONF" "$OLD"                      # -a keeps the 600 key modes
sudo chmod 700 "$OLD"
ok "old certificate backed up to $OLD"

sudo rm -f "$CONF"/mitmproxy-ca*.pem "$CONF"/mitmproxy-ca*.p12 "$CONF"/mitmproxy-ca*.cer
ok "old certificate removed"

# Generated by deploy/gen_ca.sh, NOT by letting mitmproxy make its own on restart.
# mitmproxy's CA can vouch for any hostname; this one is constrained to the gated
# domains. Rotating through mitmproxy would quietly hand back an unconstrained CA and
# nothing downstream would mention it.
rollback() {
  printf "\n${R}%s — restoring the old certificate.${N}\n" "$1"
  sudo rm -rf "$CONF"; sudo cp -a "$OLD" "$CONF"
  sudo chown -R "$PROXY_USER:$PROXY_USER" "$CONF"; sudo systemctl restart "$SERVICE"
  die "Rolled back. Your devices still trust the previous certificate."
}

# Generate BEFORE restarting, and verify before restarting too. Order matters here:
# mitmproxy makes itself a fresh UNCONSTRAINED CA when confdir is empty, so restarting
# first and checking afterwards would find a perfectly good certificate file and report
# success — having silently thrown away the constraint that is the point of this change.
sudo "$HERE/deploy/gen_ca.sh" "$CONF" 2>&1 | sed 's/^/  /' || true
sudo test -f "$CONF/mitmproxy-ca-cert.pem" || rollback "Generation failed"
sudo openssl x509 -in "$CONF/mitmproxy-ca-cert.pem" -noout -text \
  | grep -q "Name Constraints" || rollback "New certificate has no name constraints"

sudo chown -R "$PROXY_USER:$PROXY_USER" "$CONF"
sudo chmod 700 "$CONF"
sudo systemctl restart "$SERVICE"
NEWFP="$(fingerprint "$CONF/mitmproxy-ca-cert.pem")"

# Re-pin the fingerprint the hourly audit compares against.
#
# The audit notes "CA FINGERPRINT CHANGED" whenever the live CA stops matching its
# baseline, and it only ever WRITES that baseline when the file is empty (see the
# `[ -s "$PIN" ]` branch in deploy/cooldown-audit.sh). A deliberate rotation therefore
# looks exactly like the theft the pin exists to catch, and keeps looking like it every
# hour until somebody clears the file by hand.
#
# A detector that cries wolf after every legitimate rotation is one you learn to ignore,
# which is the same failure as not having it. Rotating is the one moment we KNOW the
# change was intended, so it is the right place to say so.
AUDIT_PIN="${COOLDOWN_AUDIT_PIN:-/var/lib/cooldown-audit-baseline}"
if sudo test -e "$AUDIT_PIN"; then
  printf '%s' "$NEWFP" | sudo tee "$AUDIT_PIN" >/dev/null
  sudo chmod 600 "$AUDIT_PIN"
  ok "audit fingerprint pin updated (no hourly false alarm)"
else
  say "no audit baseline at $AUDIT_PIN — the audit will pin the new one on its next run"
fi
[ "$NEWFP" = "$(fingerprint "$OLD/mitmproxy-ca-cert.pem")" ] && die "New fingerprint matches the old — rotation did not happen."
ok "new certificate generated"

cat <<EOF

${B}${G}Rotated.${N}
  new fingerprint: ${C}$NEWFP${N}
  ${DIM}old one kept at $OLD — delete once every device is on the new certificate${N}

${B}Now, on each device you route through this box:${N}
  1. Remove the OLD profile/certificate (see RECOVERY.md for where it lives).
  2. Visit ${C}http://mitm.it${N} and install the new one.
  3. ${Y}iOS also needs:${N} Settings → General → About → Certificate Trust Settings → on.

  Until you do, that device will show certificate warnings. That's expected.
EOF
